### ISSUE TITLE
【question】How to write pytest check log to allure-Report

### ISSUE THREAD

**Issue by jamesz2011** [okken/pytest-check#60] opened 2021-05-07 03:13 UTC
hello,I have a question about pytest-check,such as photo:
![image](https://user-images.githubusercontent.com/16397200/117392681-2e472f80-af25-11eb-9682-8045035deb75.png)

**Comment by okken** [comment] 2021-05-19 21:34
duplicate of #58 
Trying to work with Allure team to figure out a real solution.
Proposed solutions so far are lacking.

**Closed by okken** 2021-05-19 21:34 UTC
