### ISSUE TITLE
Support f-strings in py-check custom error messages

### ISSUE THREAD

**Issue by GrayedFox** [okken/pytest-check#74] opened 2022-01-19 11:03 UTC
I have a test like so (fixture handles sending requests and storing the response data):

    def test_something(self):
        url = self.response.data['url']
        check.is_true(url.endswith(self.extension), f'Image quality uri for device {self.device} should end with {self.extension}')

Depending on the params used for the test, the extension and device changes. This way I can feed in different parameters and still use the same test. However the output I get is as follows:

```
FAILURE: Image quality uri for device android should end with .tflite
assert False
 +  where False = bool(False)
integration/tests/test_initialize.py:64 in test_initialize_returns_correct_image_uri() -> check.is_true(url.endswith(self.extension), f'Image quality uri for device {self.device} should end with {self.extension}')
------------------------------------------------------------
Failed Checks: 1
```

I would like the f-string to properly interpolate the string with the variables, if possible 😄 

Not sure if this is a clone of #52

**Comment by rloutrel** [comment] 2022-08-24 08:59
@GrayedFox : The interpolation is done correctly (see the first line "Failure: .....").
You probably mean, that you expect the variable in the code line extract to be interpolated? Actually, I think it is not a good idea, since if you look into your code, you will probably search for the real code (the interpolation is done 3 lines above).

I would however find usefull to have a multiline command handling (if the check.is_true is split in several lines). In the bellow example, I replaced is_true with equal, to have 3 lines:

from:
```
integration/tests/test_initialize.py:64 in test_initialize_returns_correct_image_uri() -> check.equal(url.endswith(self.extension), 1, f'Image quality uri for device {self.device} should end with {self.extension}')
```
to:
```
integration/tests/test_initialize.py:64..66 in test_initialize_returns_correct_image_uri() -> 64: check.equal(url.endswith(self.extension),
65: 1,
66: f'Image quality uri for device {self.device} should end with {self.extension}')
```

It is a new request and I will create a new ticket, if you think it is possible to implement, but I though also that the original request was inapropriate and my alternative enhancement request could help understand the reason why it is how it is.

**Comment by okken** [comment] 2022-09-01 19:47
I agree that this isn't a bug. Seems to work as designed.
I haven't looked into the multiline command handling. That might be a trick. But no harm in asking.
Closing this issue.

**Closed by okken** 2022-09-01 19:47 UTC
Labels: enhancement, help wanted
